Upload sketches
UST-QuAntiL/qc-atlas pull request #125
Opened 2020-09-09 13:42 UTC by radufalcusanStoneone

#### Short Description

#### Proposed Changes

  * Create Sketch entity and CRUD operations

2020-09-10 07:25 UTC, ckrieger commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java
> +    private Sketch getSketchByAlgoIdAndSketchId(UUID algoId, UUID sketchId) {
hier können wir doch direkt auf das Sketchrepository zurgreifen mit getSketchById oder?

2020-09-10 07:25 UTC, ckrieger commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
>      //    private final TagAssembler tagAssembler;
Kommentierter Code löschen.

2020-09-10 07:25 UTC, ckrieger commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +            Sketch sketch = sketchService.addSketchToAlgorithm(algoId, file, description, baseURL);
kann man die baseURL nicht auch übers backend auslesen? Dann müssen wir sie nicht mitschicken.

2020-09-10 07:25 UTC, ckrieger commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +            produces = MediaType.IMAGE_JPEG_VALUE)
Ist das bei uns immer ein jpg?

2020-09-10 09:35 UTC, ckrieger commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +            produces = MediaType.IMAGE_JPEG_VALUE)
Hier auch mal anschauen wie die images gespeichert werden.

2020-09-10 10:07 UTC, ckrieger commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Algorithm.java
> -    private String inputFormat;
inputFormat und outputFormat in Algo definieren. Außerdem sollte Algorithm nicht von AlgorOrImpl erben.

2020-09-10 13:50 UTC, ckrieger approved these changes
LGTM

2020-09-11 17:08 UTC, FlxB2 commented
> @FlxB2 ich hab dich jetzt einfach mal als Reviewer eingetragen. Wäre super wenn Zeit für ein Review hast :)

Ich habe in letzter Zeit wenig mit dem Backend zu tun gehabt, ich übergebe das Review deshalb lieber einem Kollegen. 
Habe den anderen schon bescheid gegeben, einer wird sich dann um das Review kümmern (:

2020-09-14 07:20 UTC, T-Haller commented
@ckrieger ich habe mal den master reingeholt und die merge Konflikte beseitigt, wir haben Ende letzte Woche ein ziemlich großes Refactoring reingemerged. Bitte auch einmal noch schauen, ob das nichts kaputt gemacht hat. Ansonsten Review ich jetzt die Änderungen kurz.

2020-09-14 08:28 UTC, T-Haller reviewed
Funktional sieht das gut aus, die größten Verbesserungen sind konsistenz und einige andere Kleinigkeiten.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java
> +            throw new RuntimeException("Could not store the Sketch. Error: " + e.getMessage());
Jede Exception, die wir nicht direkt behandeln liefert HTTP Status code 500 zurrück, also würde es hier Sinn machen entweder eine existierende Exception zu verwenden, die von RuntimeException erbt, und diese in der "AtlasExceptionHandler" behandeln, falls das noch nicht der falls ist. Oder eine neue Exception zu erstellen, diese auch von RuntimeException erben zu lassen und im "AtlasExceptionHandler" zu behandeln, damit dieses Problem nicht in einem Internal Server error endet.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +            @ApiResponse(responseCode = "404", description = "Algorithm with the given id doesn't exist")
Response code 400 könnte hier auch auftreten, wenn die Id keine UUID ist z.B.
Auch 417 ist möglich siehe Zeile 616.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +    public ResponseEntity<Sketch> uploadSketch(
Eine SketchDto als Rückgaben würde hier Sinn mach um konsistent mit dem Rest des Programms zu bleiben

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +
Kurze swagger doku (operation annotation) noch hinzufügen.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +            @ApiResponse(responseCode = "404", description = "Algorithm or sketch with given id doesn't exist")
Response code 400 könnte hier auch auftreten

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +            @ApiResponse(responseCode = "200"),
das sollte 204 sein.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +
Kurze swagger doku (operation annotation) noch hinzufügen.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +            @ApiResponse(responseCode = "200")}, description = "Update the properties of a sketch.")
Hier könnte noch 400 und 404 auftreten

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +
Kurze swagger doku (operation annotation) noch hinzufügen.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java
> +    public Date creationDate;
Das attribut kann private werden.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java
> +    public Date lastModifiedAt;
Das attribut kann private werden.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Sketch.java
> +    @Exclude
Da es mehrere excludes gibt könnte man hier auch den statischen Import entfernen und 
> @EqualsAndHashCode.Exclude

daraus machen, das könnte die readability ein bisschen verbessern.

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +            produces = MediaType.IMAGE_JPEG_VALUE)
Gibt es hier einen Grund warum die annotation nicht @GetMapping ist?

2020-09-14 08:28 UTC, T-Haller commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java
> +    public Sketch update(UUID id, Sketch sketch) {
Um Rubustheit im allgemeinen zu verbessern kann man nocht lomboks "@NonNull" annotation vor parameter in methoden schreiben. Gibt viele Orte, wo man das machen könnte, daher belass ich es hier mal als einen Kommentar.

2020-09-14 08:50 UTC, radufalcusanStoneone commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Algorithm.java
Ja, genau. Die Idee ist die AlgorithmOrImplementation  Klasse komplett zu löschen, da es keinen Mehrwert bringt. Wenn das Ändern Konflikte auslöst, lassen wir es erstmal so und machen daraus ein Issue.

2020-09-14 08:56 UTC, T-Haller commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Algorithm.java
Alles klar habe ich kein Problem mit. Das sollte auch keine Probleme geben solange die Felder bei beiden Klassen drin sind, also mach bei der "Implementation" Klasse noch ein Feld für den Namen rein und las es von "KnowledgeArtifact" anstatt "AlgorithmOrImplementation" erben und dann sollte es keine Verweise mehr geben und die Klasse kann gelöscht werden.

2020-09-14 15:37 UTC, radufalcusanStoneone commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> +    public ResponseEntity<Sketch> uploadSketch(
Da die SketchEntity wenige Attribute hat, werden keine Performance Probleme entstehen. Wenn man die Konsistenz behalten will, kann man nach dem merge ein Issue erstellen, wo den SketchDto erstellt werden soll. :)

2020-09-15 08:41 UTC, LHommeDeBat requested changes

2020-09-15 08:41 UTC, LHommeDeBat commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java
> +    public void delete(UUID sketchId) {
Transactional-Annotation fehlt hier (org.springframework.transaction.annotation.Transactional)

2020-09-15 08:41 UTC, LHommeDeBat commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java
> +    public Sketch update(UUID id, Sketch sketch) {
Transactional-Annotation fehlt hier (org.springframework.transaction.annotation.Transactional)

2020-09-15 08:41 UTC, LHommeDeBat commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java
> +    public Sketch addSketchToAlgorithm(UUID algorithmId, MultipartFile file, String description, String baseURL) {
Transactional-Annotation fehlt hier (org.springframework.transaction.annotation.Transactional)

2020-09-16 07:55 UTC, LHommeDeBat approved these changes

2020-09-16 09:27 UTC, radufalcusanStoneone commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchService.java
> +public interface SketchService {
Ich habe mich an den anderen interfaces in den Projekt orientiert und die sind alle public und deswegen würde ich das erstmal so lassen, falls das für dich OK ist.

2020-09-16 09:29 UTC, radufalcusanStoneone commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchService.java
> +    byte[] getImageBySketch(final UUID sketchId);
Ich habe mich an den anderen interfaces in den Projekt orientiert und alle waren public und deswegen würde ich erstmal so lassen, falls das für dich OK ist.

2020-09-16 09:33 UTC, T-Haller commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchService.java
> +public interface SketchService {
Ja da habe ich mich nicht gut ausgedrückt, hier ging es nur um die Sichtbarkeiten bei den methoden.

2020-09-16 09:34 UTC, T-Haller approved these changes

2020-09-16 09:34 UTC, T-Haller commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/ImageRepository.java
> +    Image findImageBySketchId(@Param("sketchId") UUID sketchId);
Das "@Param("sketchId")" kann noch weg.

2020-09-16 10:29 UTC, radufalcusanStoneone commented
Branch wurde nach dem Code Review gefixt => falls es keine weitere Anmerkungen gibt, dann kann der Branch ins master gemerget werden :)

2020-09-16 11:35 UTC, merged