Refactoring/fileservice
UST-QuAntiL/qc-atlas pull request #173
Opened 2020-11-06 10:10 UTC by ckrieger

2020-11-06 12:59 UTC, salmma commented
should also be tested by S1 as we do not have google cloud storage.

2020-11-06 15:36 UTC, salmma reviewed
handling of files in ImplementationGlobalController can be deleted, or not?

2020-11-06 16:05 UTC, salmma requested changes
see comments + for POST on files with an implementationId and a jpeg I'm getting 500: 

2020-11-06T17:02:44,278 [c-10] DEBUG o.p.a.w.a.VersionedRequestHandlerMapping - Mapped to org.planqk.atlas.web.controller.ImplementationController#createFileForImplementation(UUID, MultipartFile) 
WARN  o.p.a.w.c.AtlasExceptionHandler      - source cannot be null 
java.lang.IllegalArgumentException: source cannot be null

2020-11-06 16:25 UTC, ckrieger commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/FileRepository.java
> +    @Query(value = "SELECT * " +
Hatte ich mit @wederbn besprochen. Wir wollen einen unidirectional mapping ohne join um damit die File table keine Ids von den ganzen Parents wie z.B Implementation hat. Sonst müssen wir wahrscheinlich in der Zukunft immer das Schema updaten. Wegen Paging habe ich es nur so hinbekommen. Ist eventuell nicht die beste Lösung. Falls euch noch was einfällt könnt ihr das gerne noch verbessern.

2020-11-06 16:25 UTC, ckrieger commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java
> +        @PathVariable UUID implementationId,
Hab ich gefixed

2020-11-06 16:32 UTC, ckrieger commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationGlobalController.java
> -        final File file = fileService.create(implementationId, multipartFile);
Hab ich mal noch drin gelassen, da wir es bei uns noch nutzen im frontend und man auch die Tests ändern muss. Mach ich dann in einem seperaten branch

2020-11-06 16:33 UTC, ckrieger commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/FileRepository.java
> +    @Query(value = "SELECT * " +
hast du ein update von deiner db gemacht? Das schema hat sich geändert.

2020-11-06 16:34 UTC, ckrieger commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java
> +        @PathVariable UUID implementationId,
Fixed

2020-11-10 10:36 UTC, salmma approved these changes

2020-11-10 10:37 UTC, merged