Feature/packages and fileservice
UST-QuAntiL/qc-atlas pull request #176
Opened 2020-11-16 14:20 UTC by salmma

#### Short Description
Implements Issue #162 (ImplementationPackage is not an abstract class).

#### Proposed Changes
  * Files can be accessed behind implementations/{impl-id}/implementation-packages/{impl-package-id}/...
  * CRUD operations for ImplementationPackages
  * add service and controller tests for ImplementationPackages, adapt File test
  * one to one relationship between ImplementationPackage and File

2020-11-17 14:33 UTC, ckrieger requested changes

2020-11-17 14:33 UTC, ckrieger commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/ImplementationPackage.java
> +public class ImplementationPackage extends HasId {
ist das mit Absicht extends HasId oder lieber extends KnwoledgeArtifact?

2020-11-17 14:33 UTC, ckrieger commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/ImplementationPackage.java
> +    public void download() {
macht das hier Sinn oder lieber an den service?

2020-11-18 08:25 UTC, ckrieger commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/ImplementationPackage.java
> +public class ImplementationPackage extends HasId {
Create Issue

2020-11-23 20:59 UTC, salmma commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/ImplementationPackage.java
> +    public void download() {
ist draußen

2020-11-23 21:00 UTC, salmma commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/FileService.java
> +    File create(UUID implementationPackageId, MultipartFile file);
Bindung wurde wieder rausgenommen

2020-11-23 21:01 UTC, salmma commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/FileServiceImpl.java
> +        final java.io.File newFile = new java.io.File(dir.getAbsolutePath() + java.io.File.separator + implementationPackageId + "_" +
implementationPackages sind nicht mehr im Pfad

2020-11-23 21:03 UTC, salmma commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/File.java
> +    @ToString.Exclude
wurde jetzt ebenfalls durch eine query ersetzt und die Beziehung von File nach ImplementationPackages rausgenommen

2020-12-02 11:10 UTC, ckrieger approved these changes

2020-12-02 11:10 UTC, merged