Feature/versioning
UST-QuAntiL/qc-atlas pull request #181
Opened 2021-04-05 23:11 UTC by ValeSayfa

#### Short Description
This pull request adds the functionality to create revisions of algorithms and implementations based on the envers hibernate module.

#### Proposed Changes
  * Integrates envers module in repositories and services
  * Adds ressource for revisions in algorithm and implementation controller to retrieve all revisions or a certain revision

2021-04-22 06:55 UTC, manuwei commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/AlgorithmRepository.java
> +    @Query(value = "DELETE FROM algorithm_revisions WHERE rev = :revId AND id = :algoId", nativeQuery = true)
is it absolutely necessary to use a native query here?

2021-04-22 06:58 UTC, manuwei commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/AlgorithmRevisionAssembler.java
> +public class AlgorithmRevisionAssembler extends GenericLinkAssembler<RevisionDto> {
since I'm currently removing all hal links, could you remove all new hal link logic? :)

2021-04-22 07:04 UTC, manuwei reviewed
Hey @ValeSayfa, looks good to me in general. Could have a look at the few comments that I made? After addressing these, I will test (and probably approve it) :)

2021-04-26 17:14 UTC, ValeSayfa commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/AlgorithmRepository.java
> +    @Query(value = "DELETE FROM algorithm_revisions WHERE rev = :revId AND id = :algoId", nativeQuery = true)
The Hibernate Envers API does not offer a delete functionality. Therefore, we have to use native queries for deleting revisions.

2021-04-26 21:49 UTC, ValeSayfa commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/AlgorithmRevisionAssembler.java
> +public class AlgorithmRevisionAssembler extends GenericLinkAssembler<RevisionDto> {
The new link assemblers have been deleted. I also modified the related controllers so that they are still working with the atlas ui. This should work but it should be reworked later during the hal logic removal to maintain consistency.

2021-04-27 10:05 UTC, manuwei approved these changes
LGTM, I only added some minor changes regarding the reformatting of the generated files + updated the version

2021-05-05 08:20 UTC, lharzenetter requested changes

2021-05-05 08:20 UTC, lharzenetter commented on pom.xml
> +        <!--        <dependency>
If we don't need this dependency, remove it.

2021-05-05 09:45 UTC, ValeSayfa commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/EnversConfiguration.java
> +    public static class AuditListener extends EnversPostDeleteEventListenerImpl {
This event listener prevents envers from auditing deletions. According to our requirements on versioning we decided not to record the deletion of artifacts.

2021-05-07 23:23 UTC, ValeSayfa commented on pom.xml
> +        <!--        <dependency>
unused dependencies from liquibase have been removed

2021-06-04 07:19 UTC, lharzenetter requested changes
Besides formal changes, LGTM!

2021-06-04 07:19 UTC, lharzenetter commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
> + * Copyright (c) 2020 the qc-atlas contributors.
Please revert this change and check all the changed files whether they already contain 2021.

2021-06-04 07:19 UTC, lharzenetter commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationGlobalController.java
> + * Copyright (c) 2020 the qc-atlas contributors.
see above

2021-06-04 07:19 UTC, lharzenetter commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/RevisionDto.java
> +package org.planqk.atlas.web.dtos;
In this file the license header is missing completely. Please check your IntelliJ configuration and ensure that you have enabled the autoated generation of license headers.

2021-06-04 07:19 UTC, lharzenetter commented on pom.xml
> +  ~ Copyright (c) 2020 the qc-atlas contributors.
see above

2021-06-10 07:22 UTC, lharzenetter approved these changes

2021-06-10 07:28 UTC, merged