Task 187
UST-QuAntiL/qc-atlas pull request #194
Opened 2021-07-12 07:48 UTC by emymaria

#### Short Description

Link Builder Class - Link Builder class used hateoas. Deleted this class. It was used in a single method in link builder service,
					this method had usages only in link builder service test. So I assume it is safe to delete the class.
					All the tests both in core and web passed after deleting also. 

#### Proposed Changes

  * Deleted the LinkBuilder Class
  * Removed the method in LinkBuilderService that used the LinkBuilder Class
  *Removed 3 tests from LinkBuilderServiceTest class that used the deleted method in LinkBuilderService

**Fixes**: #

2021-07-12 08:05 UTC, salmma requested changes
- Please remove unused imports in LinkBuilderServiceTest
- Remove hateoas [Links](https://github.com/UST-QuAntiL/qc-atlas/blob/5fe2dfb084d0ec1f3087a15cd289c75934b9a9e3/org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/EntityModelConverter.java#L25)
- check if [HateoasSortHandlerMethodArgumentResolver](https://github.com/UST-QuAntiL/qc-atlas/blob/5fe2dfb084d0ec1f3087a15cd289c75934b9a9e3/org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/ListParametersMethodArgumentResolver.java#L45) can be removed

2021-07-12 08:11 UTC, manuwei requested changes
The removal of the LinkBuilder is fine :) 
Can you have at all imports with "hateoas" again? I think there are still imports/occurences in the code that can be removed, 
e.g., @Relation annotations and `addLinks(...)` we add hateoas links to an entity

2021-07-12 11:58 UTC, emymaria commented
> * Please remove unused imports in [LinkBuilderServiceTest](https://github.com/UST-QuAntiL/qc-atlas/blob/9b44a89b7a9476fae7f96b86664abfe5a91a12a8/org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/linkassembler/LinkBuilderServiceTest.java)
> * Remove hateoas [Links](https://github.com/UST-QuAntiL/qc-atlas/blob/5fe2dfb084d0ec1f3087a15cd289c75934b9a9e3/org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/EntityModelConverter.java#L25)
> * check if [HateoasSortHandlerMethodArgumentResolver](https://github.com/UST-QuAntiL/qc-atlas/blob/5fe2dfb084d0ec1f3087a15cd289c75934b9a9e3/org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/ListParametersMethodArgumentResolver.java#L45) can be removed

2021-07-12 12:02 UTC, emymaria commented
Hallo
I removed remove unused imports in LinkBuilderServiceTest.
Removed hateoas.Links - Links was used in EntityModelConverter class which was in turn used in swagger configuration. Removed that part of swagger configuration and tested the swagger to find it working fine. So I deleted EntityModelConverter and its test class. Also I find it safe to delete OverrideModelConverter class and its test class also.
remove @relation annotations and addLinks(...)  - After new build I could not find these keywords, so I assume it got removed

2021-07-12 12:56 UTC, salmma requested changes
- Please remove your out-commented code
- check if the [LinkRemoverModelController](https://github.com/UST-QuAntiL/qc-atlas/blob/5b357ebbfb5dab98da982a480d93412e2ab03a8f/org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/LinkRemoverModelConverter.java#L39) can be removed
- check if [OverrideModelConverter](https://github.com/UST-QuAntiL/qc-atlas/blob/5b357ebbfb5dab98da982a480d93412e2ab03a8f/org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/OverrideModelConverter.java#L40) can be removed
- check if further classes/methods can be removed in context of HATEOAS :)

2021-07-13 11:42 UTC, manuwei commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/EntityModelConverter.java
> - * EntityModel-specific fields (for now, just _links).
did you do some manual testing to check if the entitys are still generated/saved/outputted correctly?

2021-07-13 11:45 UTC, manuwei requested changes
I also added some further remarks about the changes :) can you have  a look at them?

2021-07-13 11:45 UTC, manuwei commented on org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/utils/EntityModelConverterTest.java
> -public class EntityModelConverterTest {
although we do not add hateoas links to our entities anymore, I think we still need a test for entity model converting

2021-07-14 10:21 UTC, emymaria commented
I find that the LinkRemoverModelController and OverrideModelConverter can be removed. These were used in swagger configuration. Since I removed certain configurations in swagger that use these deleted class, I am testing the swagger. It is in progress. I have checked first 10 apis. I wonder if I have to test every single one or are there any high priority ones that I can test.

2021-07-15 15:06 UTC, salmma requested changes
LG - however, please add documentation as comment on top of the LinkBuilderService class to clarify that this class is used to avoid hard-coded urls in all ControllerTests.

2021-07-15 15:13 UTC, manuwei approved these changes

2021-07-16 15:26 UTC, emymaria commented
Added comments in LinkBuilderService on where the class is used

2021-07-19 09:04 UTC, salmma approved these changes
LGTM

2021-07-19 09:05 UTC, merged