134 bug sort
UST-QuAntiL/qc-atlas pull request #195
Opened 2021-07-27 10:48 UTC by emymaria

#### Short Description
Sort List of Problem Types by Parent Problem Type Name. Getting 500 error on sort request.

#### Proposed Changes
Added logic to sort based Parent Problem Type Name. Parent Problem Type is a UUID type field, so first we have to fetch corresponding names using the UUIDs and then sort.

  *
  *
  *

**Fixes**: #

2021-07-29 09:34 UTC, lharzenetter requested changes

2021-07-29 09:34 UTC, lharzenetter commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
> +        for (Sort.Order order : pageable.getSort()) {
Why do you iterate over the orders? I guess if there are more than one orders given, not the latest sort, but all should be applied...

2021-07-29 09:34 UTC, lharzenetter commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
> +        for (ProblemType eachProblemType : unSortedlistOfProblemTypes) {
The naming of `eachProblemType` is misleading. Just call it `problemType`.

2021-07-29 09:34 UTC, lharzenetter commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
> +            if (parentProblemTypeMap.containsKey(name)) {
This code depends on the name. Thus, you can move it into the first if and move the name delcaration to line 91. This way, you also avoid null pointers (if some TreeMap implementation does not support checking for null keys).

2021-07-29 09:36 UTC, salmma requested changes
given more than 10 problem types + items per page is set to 10.
When changing the ordering several times, more than the 10 items are shown, see video

https://user-images.githubusercontent.com/23473511/127469101-7b67c4af-40af-4484-a5ca-911803bb616a.mov

2021-08-01 12:54 UTC, emymaria commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
> +        for (Sort.Order order : pageable.getSort()) {
From the application we request for sort based on a single property only, but Pageable::getSort will give a Sort type, and that is an Iterable of Sort.Orders. So need to iterate over each of these to get the property and direction of sort.

2021-08-01 12:54 UTC, emymaria commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
> +        for (ProblemType eachProblemType : unSortedlistOfProblemTypes) {
Changed

2021-08-01 12:54 UTC, emymaria commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
> +            if (parentProblemTypeMap.containsKey(name)) {
In the application, it is possible to create problem type with no parent type. So we have to deal with null value of parentProblemType while sorting. Here we give it first position for ascending and opposite for descending. TreeMap can handle the null key while sorting which is why it is used.

2021-08-01 12:55 UTC, emymaria commented
Added code to limit the number of problem types returned according to page size from frontend.

2021-08-03 09:16 UTC, salmma approved these changes
LG at UI side

2021-08-03 12:25 UTC, lharzenetter commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
> +                new TreeMap<String, List<ProblemType>>(
As of Java 7, you can sipmly use the `<>` operator instead of repeating the generics in this line again.

2021-08-04 10:26 UTC, emymaria commented on org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
> +                new TreeMap<String, List<ProblemType>>(
Done

2021-08-06 15:21 UTC, lharzenetter approved these changes

2021-08-06 15:21 UTC, merged