Feature/tosca applications
UST-QuAntiL/qc-atlas pull request #209
Opened 2022-02-09 16:29 UTC by mar-be

#### Short Description
This PR adds the functionality to upload applications as CSARs. The qc-atlas uses the winery for storage and management of the uploaded applications.

#### Proposed Changes
  * add WineryService
  * add controllers, services, and repositories for Tosca applications and service templates
  * add properties and environment variables for the configuration of the WineryService

2022-02-10 09:18 UTC, salmma reviewed
- would be nice if we could have some **tests** for the new interface
- what is the status of the UI? Has the union been tested yet? @PhilWun ?
- we require (UI) **documentation** about the feature in our [readthedocs](https://github.com/UST-QuAntiL/quantil-docs)
- (quantil-docker update for winery and env variables)

2022-02-10 09:18 UTC, salmma commented on .docker/application.properties.tpl
> +# Winery
please add env variables and winery to the quantil docker-compose @lharzenetter you agree?

2022-02-10 09:59 UTC, lharzenetter requested changes
Please update the License headers to the current year.

2022-02-10 09:59 UTC, lharzenetter commented on .docker/application.properties.tpl
> +# Winery
yes

2022-02-10 09:59 UTC, lharzenetter commented on org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ToscaApplicationController.java
> +            @ApiResponse(responseCode = "404", description = "Not Found. TOSCA application  with given ID doesn't exist.")
I guess there are two spaces between `application` and `with`

2022-02-10 09:59 UTC, lharzenetter commented on org.planqk.atlas.web/src/main/resources/application.properties
> +spring.servlet.multipart.max-file-size=500MB
Maybe also make this configurable via environment variables in the Docker setup in case we have to process larger files.

2022-02-10 14:36 UTC, mar-be commented on .docker/application.properties.tpl
> +spring.servlet.multipart.max-file-size=500MB
Without being set, the default size is too small for the upload of most CSARs. 500MB is larger than all CSARs we have. Probably 200MB is also enough.

2022-02-10 14:37 UTC, mar-be commented on org.planqk.atlas.web/src/main/resources/application.properties
> +spring.servlet.multipart.max-file-size=500MB
I have added it

2022-02-11 07:18 UTC, lharzenetter approved these changes

2022-02-11 07:19 UTC, merged